steps:
  - label: "Show gif :lower_left_paintbrush:"
    commands: 
      - "buildkite-agent artifact upload partridge.gif"
      - "./log_image.sh artifact://partridge.gif"
      
  - label: "Show URL in log"
    commands:
      - "./inline_link.sh https://www.buildkite.com"
      - "./inline_link.sh https://buildkite.com/unblock"

  - label: "Log group examples"
    commands:
      - "echo '--- This creates a new log group :white_check_mark:' && cat lorem-ipsum.txt"
      - "echo '~~~ This log group will be de-emphasized :no_entry:' && cat lorem-ipsum.txt"
      - "echo '+++ This log group will be maximized :star2:' && cat lorem-ipsum.txt"
