steps:
  - label: "Show gif :lower_left_paintbrush:"
    commands: 
      - "buildkite-agent artifact upload partridge.gif"
      - "./log_image.sh artifact://partridge.gif"
      
  - label: "Show URL in log"
    commands:
      - "./inline_link.sh https://www.buildkite.com"
      - "./inline_link.sh https://buildkite.com/unblock"
